### ISSUE TITLE
Polcoin

### ISSUE THREAD

**Issue by pdrobek** [SuperNETorg/Iguana-application#13]
Hi

I read info on reddit. Im representing polcoin dev team. Please include Polcoin in your wallet.

Thank you

**Comment by imboogieman** [comment]
@pdrobek 
Thank you for your request. 
As you know, we want to keep Iguana a trusted tool in the market, so we need to make sure all service we provide is secure enough for users.
Can you, pls, provide some fresh links to mentions in any credible resources and status update on the development of Polcoin core?

**Comment by imboogieman** [comment]
Closed due to lack of credibility provided.
