### ISSUE TITLE
observing background image isn't available on production version of gui

### ISSUE THREAD

**Issue by kashifali007** [SuperNETorg/Iguana-application#19]
observing background image isn't available on production version of gui whereas dev version is working fine. without background image, gui looks blur and very hard to read the contents of login page.

snapshot is attached for your perusal. 

Thanks,
-Kashif Ali

![iguana-gui](https://cloud.githubusercontent.com/assets/16662663/21098407/f5ee78f6-c08a-11e6-9947-6d7a28ed366a.png)

**Comment by pbca26** [comment]
@kashifali007 should be fixed by now
please pull the latest and let me know if the issue still persist

**Comment by kashifali007** [comment]
verified-fixed. we can close it now
