### ISSUE TITLE
Groom the readme file to make the text look neat.

### ISSUE THREAD

**Issue by imboogieman** [SuperNETorg/Iguana-application#23]
- Make an ordered list Non-Iguana wallet requirements
- Structure the text

**Comment by imboogieman** [comment]
@ed888 
see no changes 
https://github.com/SuperNETorg/Iguana-application/commits/develop/README.md

**Comment by ed888** [comment]
@imboogieman will you please check it on this branch http://i.prntscr.com/51402edb14bd49b381122b73ee725fad.png
It hasn't been merged with develop yet. 
If you still need changes, let me know please.
