### ISSUE TITLE
user can create a wallet without passing gui generated passphrase

### ISSUE THREAD

**Issue by kashifali007** [SuperNETorg/Iguana-application#27]
user can create a wallet without passing gui generated passphrase. infact user can type own passphrase to create a wallet.

Steps to reproduce:
1. Run any coind without running encrypted wallet
2. open up index.html file 
3. Click on wallet create button 
4. You will be seeing gui generated passphrase, don't copy it, infact type your own passphrase 
5. Hit enter Accpet button and you will observing a dialog box open indicating you have been successful to create wallet.

-Kashif Ali

**Comment by ed888** [comment]
@kashifali007 @imboogieman I couldn't reproduce the above mentioned issue. Can you please test it again and make a short video if the issue is still actual?

**Comment by kashifali007** [comment]
@ed888 

i can reproduce the issue. just type hello hello hello hello hello hello hello hello hello hello hello hello or any passphrase you like it but don't copy the gui generated passphrase and create the wallet. once wallet is to be created then you can login back with the same passphrase. it mean i can create wallet without gui generated passphrase

cc: @imboogieman @pbca26

**Comment by pbca26** [comment]
@kashifali007 yes i can do the same as well. Typed "1234" and gui accepted that passphrase on "create wallet verify passphrase" step. That's a major bug.

**Comment by ed888** [comment]
@kashifali007 It's done, please check.

**Comment by kashifali007** [comment]
verified-fixed. nice work!

**Comment by ed888** [comment]
@kashifali007 thank you
