### ISSUE TITLE
User is unable to login if the wallet is created with user generated passphrase

### ISSUE THREAD

**Issue by kashifali007** [SuperNETorg/Iguana-application#28]
User is unable to login if the wallet is created with user generated passphrase.
This issue is the ripple effect of previous issue when user creates wallet with user generated passphrase instead of gui generated.

Steps to reproduce:
1. Run coind which you had created wallet
2. open up index.html file
3. click on login button and enter the passphrase which you typed to create wallet

Here you will be observing nothing. Neither login will successful nor any error message pop up. 

-Kashif Ali

**Comment by imboogieman** [comment]
@kashifali007 
Iguana or Non-Iguana Mode or both?

**Comment by kashifali007** [comment]
@imboogieman both

**Comment by arkadig** [comment]
@imboogieman @kashifali007 I tested this and got the following result: I tried to create  a wallet and typed my own passphrase. I got this error message: http://i.prntscr.com/6295f4d0233a48229523b945d576d835.png
 Is this ok? If yes the ticket can be consider not actual.

**Comment by kashifali007** [comment]
it can be closed basically this issued has been fixed. user you are not allowed to enter passphrase
