### ISSUE TITLE
gui doesn't throw any error is passphrase is less 12 words

### ISSUE THREAD

**Issue by kashifali007** [SuperNETorg/Iguana-application#29]
gui doesn't throw any error is passphrase is less 12 words

Steps to reproduce:
1. run cond with encrypted wallet
2. open up the index.html in browser
3. click on login button
4. type passphrase less than 12 words

you will be observing here no error message pop indicating what went wrong. it would be really hard for user to figure out the issue. so error message indicating real issue should be thrown by gui

-Kashif Ali

**Comment by imboogieman** [comment]
@kashifali007 
Iguana or Non-Iguana Mode or both?

**Comment by pbca26** [comment]
@kashifali007 probably user story hasn't been updated yet. Login screen only checks if passphrase field is longer than 1 character. We discussed it with @imboogieman several times already. Passphrase can be any length or complexity. The only thing that we agreed to verify is generated passphrase length on create wallet step.

**Comment by kashifali007** [comment]
okay so generated passphrase will be min 12 characters long. but what if user want to create wallet with own generated passphrase? what would be the length of passphrase then? @pbca26 @imboogieman

**Comment by pbca26** [comment]
@kashifali007 this is not possible to do via gui. Only if you use qt wallet/iguana with curl or cli.

**Comment by kashifali007** [comment]
@pbca26 i can create wallet with my own passphrase and login back as well

**Comment by kashifali007** [comment]
via gui

**Comment by pbca26** [comment]
@kashifali007 if that's true then it's a bug
users should be able to create their own passphrases via gui

**Comment by arkadig** [comment]
@pbca26 @kashifali007 I think the ticket isn't already actual and it can be considered closed. Am I right or missing something?

**Comment by kashifali007** [comment]
can be closed!
