### ISSUE TITLE
Chrome app bugs

### ISSUE THREAD

**Issue by pbca26** [SuperNETorg/Iguana-application#30]
Mobile
1) Pages are unscrollable
2) Top menu styling is breaking
3) Top menu disappears in tx only mode view

Settings page throws an error and doesn't render

**Comment by pbca26** [comment]
@arkadig please review the list of bugs and let me know which one you can confirm on your end.

**Comment by arkadig** [comment]
@pbca26 I reproduced only 
1. Pages are unscrollable
I have fixed it , but don't think it's a best solution....
please check and let me know what you think.

can't reproduce 2. and 3.
