### ISSUE TITLE
Last row of coins is hidden/semi-hidden in add coin modal

### ISSUE THREAD

**Issue by pbca26** [SuperNETorg/Iguana-application#31]
I'm unable to see all coins. Part of the modal is filled with gradient which prevents me from seeing bottom coins. This affects all resolutions.

![add-coin-modal-scroll1](https://cloud.githubusercontent.com/assets/7769879/21604370/e31ee230-d1b3-11e6-9bdd-379a17dcf77d.png)
![add-coin-modal-scroll2](https://cloud.githubusercontent.com/assets/7769879/21604376/ede4d7e2-d1b3-11e6-9b59-3b4dccb7fe6b.png)

**Comment by pbca26** [comment]
Also, DEM container's height is bigger than other coins.

**Comment by pbca26** [comment]
fixed
@ed888 @arkadig can you verify that both issues are fixed on your end?

**Comment by arkadig** [comment]
@pbca26 Regarding DEM container I cannot test it as I don't have that coin. 
I can see the shadow effect on the last row of the coins when the modal is fully scrolled down
http://i.prntscr.com/1244ca6be78346a68ad2aae8bac2b003.png

**Comment by pbca26** [comment]
@arkadig thanks this part was left unnoticed. Added extra fix. Can you check one more time?

**Comment by arkadig** [comment]
@pbca26 checked. It's fixed. Thanks
