### ISSUE TITLE
An invalid error message is being thrown upon entering invalid passphrase

### ISSUE THREAD

**Issue by kashifali007** [SuperNETorg/Iguana-application#32]
to: @arkadig 

An invalid error message is being thrown upon entering invalid passphrase. Now upon entering invalid passphrase gui throws an error indicating there are no daemons running but indeed daemons are running behind the scene. 

The error message should be something like "Invalid passphrase, please try again" or "passphrase you just entered doesn't match" or "passphrase doesn't exit" could be anything meaning ful

Thanks,
-Kashif Ali

**Comment by arkadig** [comment]
@kashifali007 ok, will go through

**Comment by arkadig** [comment]
@kashifali007 done, please check

**Comment by kashifali007** [comment]
@arkadig verified-fixed. closing it

**Comment by arkadig** [comment]
@kashifali007 Thank you
