### ISSUE TITLE
Fee settings bar shows wrong info

### ISSUE THREAD

**Issue by pbca26** [SuperNETorg/Iguana-application#33]
![doge-btc-fees](https://cloud.githubusercontent.com/assets/7769879/21927196/15e814fe-d996-11e6-9b0b-414593308ceb.png)
![btc-1-option](https://cloud.githubusercontent.com/assets/7769879/21927514/fca05af0-d996-11e6-9c54-de977d798882.png)

I can see all 4 fee options enabled with altcoins used as active coin. And vice versa, I bumped into an issue when BTC had only one option enabled all other 3 disabled.

To reproduce case 1:
Add BTC and another coin.
Select btc on dashboard as an active coin.
Refresh the page.
Select altcoin you added as an active coin.
Press send button.
You should see 4 fee options enabled.

To reproduce case 3:
Add BTC and another coin.
Select altcoin on dashboard as an active coin.
Refresh the page.
Select btc as an active coin.
Press send button.
You should see only 1 fee option enabled.

**Comment by pbca26** [comment]
@arkadig fixed. Can you verify it on your end?

**Comment by arkadig** [comment]
@pbca26 it's fixed. Thanks
