### ISSUE TITLE
Create wallet in iguana mode doesn't work properly

### ISSUE THREAD

**Issue by pbca26** [SuperNETorg/Iguana-application#34]
![create-wallet-iguana](https://cloud.githubusercontent.com/assets/7769879/21929688/2214521c-d9a3-11e6-9ed7-a7a602c11a18.png)

After I go through all "create wallet" steps in Iguana mode gui says that the wallet is encrypted. In reality I get a console error and see that encryptwallet API wasn't called at all. See screenshot for details.

Implementation is missing addcoin call. Without it the wallet cannot be encrypted.

**Comment by pbca26** [comment]
@kashifali007 can you verify the fix? Branch 0.3

**Comment by kashifali007** [comment]
verifying..

**Comment by pbca26** [comment]
@kashifali007 i added a fix to the issue you reported yesterday
> the weird thing is that when i try to login to newly created wallet i don't see the coin in the list.

please verify that it's fixed now

**Comment by ed888** [comment]
@pbca26 it works, thanks
