### ISSUE TITLE
Chrome app shows flow modal in Iguana mode

### ISSUE THREAD

**Issue by pbca26** [SuperNETorg/Iguana-application#35]
![chrome-app-iguana](https://cloud.githubusercontent.com/assets/7769879/21930308/68a5cd0c-d9a6-11e6-86fb-64728b1371e0.png)

It should not be displayed at all in Iguana mode. Only in coind.

**Comment by pbca26** [comment]
@arkadig i pushed chrome storage fix
could you verify that it's working on your end?

**Comment by arkadig** [comment]
@pbca26 I went through this and the main issue's fixed. 
I have already fixed another issue so Chrome app needs to be published. 
Another issue which I came across is that Receive and Send modals aren't opened in Chrome App about which I have written on chromedev channel.
