### ISSUE TITLE
Observing blur screen when we add new daemon wallet through dashboard

### ISSUE THREAD

**Issue by kashifali00** [SuperNETorg/Iguana-application#39]
Observing blur screen when we add new daemon wallet through dashboard

steps to reproduce:

1. run daemons ( i was running two daemons sys and dogecoin)
2. Navigate to iguana gui
3. Login to wallet
4. Click on Add Wallet button
5. Click on Coin daemon >> when login passphrase text area will be visible, just click on back arrow button 
here you will be observing blur screen

![lastestblur](https://cloud.githubusercontent.com/assets/18286977/22259241/5657b9d8-e286-11e6-9e78-61b90a0c9dbc.png)

**Comment by ed888** [comment]
@kashifali00 done, please test

**Comment by kashifali00** [comment]
I can still observe this issue but randomly. so I mark this verfied-failed
![again blur](https://cloud.githubusercontent.com/assets/18286977/22394834/2ae20ab4-e54d-11e6-8efb-0cdc6c48777b.png)

**Comment by imboogieman** [comment]
closed as related to non-iguana mode.
