### ISSUE TITLE
Iguana OS X dock icon is a bit large

### ISSUE THREAD

**Issue by miketaz100** [SuperNETorg/Iguana-application#40]
The icon is noticeably larger than all other apps on the dock. It's strictly an aesthetics issue but it should be looked at.

![screen shot 2017-01-24 at 5 25 32 pm](https://cloud.githubusercontent.com/assets/15162658/22269628/350167ce-e25a-11e6-9da0-3857369a7d8d.png)
![screen shot 2017-01-24 at 5 26 28 pm](https://cloud.githubusercontent.com/assets/15162658/22269653/4eb83ae4-e25a-11e6-8555-f36a7779fa96.png)

**Comment by satindergrewal** [comment]
@pbca26 please close this issue here.
created it in it's relevant repo: https://github.com/SuperNETorg/iguana/issues/7

**Comment by pbca26** [comment]
@satindergrewal thanks
