### ISSUE TITLE
OS X: After installation ask "Do you want to open Iguana App now"?

### ISSUE THREAD

**Issue by rnr-ikt** [SuperNETorg/Iguana-application#41]
Please add the question after installation finish, if the user want to open/launch the app. Yes/No!

Yes => Open iguana

**Comment by satindergrewal** [comment]
I'm not sure if I can make it Yes/No open app, but I know I can make it just open after installation finishes. I'll still look for the yes/no option anyway.

**Comment by satindergrewal** [comment]
@pbca26 please close this issue here.
I made it's under iguana repo:
https://github.com/SuperNETorg/iguana/issues/6

**Comment by pbca26** [comment]
@satindergrewal  thanks
