### ISSUE TITLE
What´s that spinning process? Name it...

### ISSUE THREAD

**Issue by rnr-ikt** [SuperNETorg/Iguana-application#43]
What this spinning process do? Syncing? Which mode? How long more? Which files? How many MB? 

![spinning](https://cloud.githubusercontent.com/assets/24645935/22282462/76660fe2-e2d4-11e6-8679-fc2667509b71.png)

**Comment by pbca26** [comment]
@rnr-ikt partially fixed. Progress bar is added, now you should be able to check on syncing progress.

**Comment by imboogieman** [comment]
@satindergrewal are you going to implement EasyDEX features in this release? Shall we enable the link or hide it for the future release, when we implement fully tested exchange features?
