### ISSUE TITLE
Iguana-Wallet, Menu => EasyDEX => Link broken

### ISSUE THREAD

**Issue by rnr-ikt** [SuperNETorg/Iguana-application#44]
After click for switch to EasyDEX (at the menu) broken link:

"Cannot GET /gui/Iguana-GUI/index.htmlEasyDEX-GUI/index.html"

After that, need to close Iguana and open again!

![iguana_wallet_dex_link](https://cloud.githubusercontent.com/assets/24645935/22282583/4c116704-e2d5-11e6-96bf-7fc18ab1be9b.png)

**Comment by pbca26** [comment]
@rnr-ikt fixed

**Comment by imboogieman** [comment]
@satindergrewal are you going to implement EasyDEX features in this release? Shall we enable the link or hide it for the future release, when we implement fully tested exchange features?

**Comment by satindergrewal** [comment]
@imboogieman Let's keep the links alive and show 'Coming soon' there if the feature is in deveopment, or fairly coming soon. EasyDEX page of EasyDEX-GUI now says coming soon as I'm going to work on it after main release.
let me know what you think.
