### ISSUE TITLE
Wallet (KMD) => Added coin (BTC) => Logout => Login => BTC disappeared

### ISSUE THREAD

**Issue by rnr-ikt** [SuperNETorg/Iguana-application#45]
After I have logged in with my KMD wallet, added coin (BTC), logged out and logged in... the additional coin (BTC) disappeared (not saved). 

![added coin disappeared](https://cloud.githubusercontent.com/assets/24645935/22282800/86173d1a-e2d6-11e6-92e6-11043a9c29e2.png)

**Comment by imboogieman** [comment]
@rnr-ikt it was not saved, as now adding a coin works just for Full Node, so sync has started and you killed it by closing the app. Will be okay, when Lite mode is supported.
