### ISSUE TITLE
Error message appearing indicating no daemon running despite running daemon

### ISSUE THREAD

**Issue by kashifali00** [SuperNETorg/Iguana-application#46]
Error message appearing indicating no daemon running despite running daemon. I guess this issue is appearing while running iguana core and daemon altogether.

Steps to reproduce:
1. run any coind
2. run iguana core
3. Click on login button

you will be observing error message
![Uploading error.png…]()

**Comment by imboogieman** [comment]
Closed as related to non-iguana mode.
