### ISSUE TITLE
unable to login wallet running on coind if we run iguana core in parallel

### ISSUE THREAD

**Issue by kashifali00** [SuperNETorg/Iguana-application#47]
i came across an issue let me explain the scenario. I was running two daemons syscoind and dogecoind. created wallet on syscoind meanwhile ran iguana core as well. now click on login button and select syscoin from the list. when i enter passprase to login to syscoin wallet; observed that another wallet was created on iguana core for syscoin. issue here is that i should have login to wallet running on syscoind not the iguana core.
wallet was created before running iguana core

steps to reproduce:
1. run syscoind (or any coind daemon you have)
2. Create wallet on coind
3. run iguana core ../agents/iguana 
4. refresh iguana gui
5. click on login button
6. select syscoin or whatever coin's wallet you had created in step 2
7. Enter the passphrase you had generated in step(2)
8. Click Next button

you will be observing syscoin start syncing on iguana core instead of getting login to syscoind

**Comment by imboogieman** [comment]
Closed as coinds mode support has been terminated for a period.
