### ISSUE TITLE
Less coins shown in the list then supported

### ISSUE THREAD

**Issue by imboogieman** [SuperNETorg/Iguana-application#48]
I see only 15 coins shown in the list when creating a coin. By the moment Iguana must support 30 of them.
Pls, check the list (https://goo.gl/cGlRLg) to compare and fix.

![less coins shown in the list then supported](https://cloud.githubusercontent.com/assets/16269033/22308030/5f874f84-e356-11e6-952c-f632c23b92b4.png)

**Comment by pbca26** [comment]
@imboogieman Iguana Supported Coins != Iguana Core supported coins. 40 listed coins in the spreadsheet supported ONLY in coind mode.

these are all coins that IC supports https://github.com/jl777/SuperNET/blob/master/iguana/coins/allofus

**Comment by pbca26** [comment]
@imboogieman can i close this down?
