### ISSUE TITLE
Correct coins colors and coin cards styling.

### ISSUE THREAD

**Issue by imboogieman** [SuperNETorg/Iguana-application#49]
Coins icon colour and styling is slightly different from ones on the resource files.

Now I see this.
![less coins shown in the list then supported](https://cloud.githubusercontent.com/assets/16269033/22308189/fe2a9b1e-e356-11e6-8d5b-aa1c6f76a541.png)

How they must look like
![reating_a_new_wallet_01_3_web](https://cloud.githubusercontent.com/assets/16269033/22308229/2e2b8698-e357-11e6-9a63-e2e8d5bf0ab0.png)

**Comment by imboogieman** [comment]
@ed888 
Tested it with new changes.
Now icons remain with pale colours and arranged in columns by colours: yellow, blue, green, orange.

**Comment by pbca26** [comment]
@imboogieman that's an old coin font
we need to compile a new one or use svg for that
i'll try to add either option tomorrow
don't have an access to mac now

**Comment by pbca26** [comment]
@ed888 I already added 40+ coin svg in color here https://github.com/SuperNETorg/Iguana-GUI-font/tree/master/svg/color
but I'm still waiting on anton to fix doge coin. I'll keep you updated when you can proceed with this task.

**Comment by ed888** [comment]
@pbca26 thanks for the update

**Comment by pbca26** [comment]
@ed888 added doge. https://github.com/SuperNETorg/Iguana-GUI-font. You should have everything to finish the task.
Make sure to use both fonts, svg for add coin modal and a regular b&w ttf for the sidebar and send coin modal.
You'd need to make modifications to gulp tasks as well.
To see all coins at once just this line to your local dev.js file
`dev.showAllCoindCoins = true;`
Run coind mode to verify that all coins in add coin modal are in color.

**Comment by imboogieman** [comment]
@pbca26 @ed888 
what logic is applied for the coins order? From A to Z, from biggest in blockchain sizes to smallest? no logic? Pls, apply from A to Z.

But despite any logic, KMD must be placed the first in the top left corner, always.

**Comment by pbca26** [comment]
verified, closing
