### ISSUE TITLE
Wrong creating an Iguana account flow

### ISSUE THREAD

**Issue by imboogieman** [SuperNETorg/Iguana-application#50]
To create an Iguana account

0. Given I chose Iguana mode
1. I click on the create account button
2. I see a generated 24-word passphrase
3. I confirm I have saved the passphrase
4. I provide the passphrase to encrypt Iguana account
5. An account is created
6. Now I can add other coins.

Step 01
![wrong creating an iguana account flow 01](https://cloud.githubusercontent.com/assets/16269033/22309161/230d8eec-e35b-11e6-98f3-921e07caebca.png)

Step 02
![wrong creating an iguana account flow 02](https://cloud.githubusercontent.com/assets/16269033/22309167/291198c4-e35b-11e6-8ef1-740048267ff5.png)

Step 03
![wrong creating an iguana account flow 3](https://cloud.githubusercontent.com/assets/16269033/22311061/bbd24a9e-e362-11e6-90ff-fc45abf7f388.png)

**Comment by pbca26** [comment]
@ed888 modify the flow to preselect KMD as a default coin. At this point we restrict create wallet flow in iguana mode to force use KMD. Lets allow users to select multiple coins but they shouldn't be able to unselect KMD on create wallet step. 

Let me know if you need to clarify this further.

**Comment by ed888** [comment]
@imboogieman @pbca26 done, please check

**Comment by ed888** [comment]
@imboogieman @pbca26 done, please check

**Comment by imboogieman** [comment]
@ed888 
**Wrong:**
Given I selected coins to add
When I proceed
Then the app kicks me out 
And It shows the message the coins were created
And It asks to login.

**Right:**
Given I selected coins to add
When I proceed
Then the app shows the message the coins were created
And It logs me in
And I am redirected to the dashboard
And I see the coins I created/added on the dashboard

**N.B.: Mind that now when a coin is added, it is added as  Full Node and must start syncing in the background. The progress bar  is coming.**

**Comment by imboogieman** [comment]
@pbca26 did you push DIY progress bar yet?

**Comment by pbca26** [comment]
@imboogieman yes
i added it yesterday

**Comment by ed888** [comment]
@pbca26 @imboogieman done the autologin part as well, please check

**Comment by imboogieman** [comment]
@pbca26 @ed888 
I see the changes only in the header text.
The app still kicks me out when an account is created and asks to login.

Double or triple or quadruple check before committing. It takes to track the same bugs over and over.

**Comment by ed888** [comment]
@imboogieman ok, will chcek

**Comment by ed888** [comment]
@imboogieman ohh, the message was wrong, now fixed.
