### ISSUE TITLE
Wrong automatic passphrase entry

### ISSUE THREAD

**Issue by imboogieman** [SuperNETorg/Iguana-application#52]
**Wrong:**
Given I confirmed that I had saved a passphrase
When I am redirected to passphrase confirmation page
Then I see the passphrase is entered
And the next (create) button is enabled

![wrong automatic passphrase entry](https://cloud.githubusercontent.com/assets/16269033/22310830/96cb6254-e361-11e6-92a1-dfcdabb402ae.png)

**Right**
Given I am redirected to passphrase confirmation page
Then I see the passphrase field empty
And the next (create) button is disabled

![reating_a_new_wallet_01_6_web](https://cloud.githubusercontent.com/assets/16269033/22310499/8b0ed05a-e360-11e6-96b0-d1c608be978d.png)

**Comment by ed888** [comment]
@imboogieman Done, please check

**Comment by pbca26** [comment]
closing, verified as fixed
