### ISSUE TITLE
Wrong proxy setup error message

### ISSUE THREAD

**Issue by imboogieman** [SuperNETorg/Iguana-application#53]
**Wrong:**
Given I am on passphrase confirmation
When I stay still for sometime (more than 60-100 seconds)
Then I see the proxy error message

![wrong proxy error message when in iguana mode](https://cloud.githubusercontent.com/assets/16269033/22310857/bf225afa-e361-11e6-868d-3d53ea5107bb.png)

**Right:**
No proxy setup error messages in Iguana mode

**Comment by imboogieman** [comment]
The  bug remains, the text of the error message now different )

![wrong proxy setup error message_01](https://cloud.githubusercontent.com/assets/16269033/22589284/995b6b80-ea1a-11e6-8913-fba5ad71292f.png)

**Comment by ed888** [comment]
@imboogieman I am not able to reproduce this. Can you please check and let me know if it is still actual.
