### ISSUE TITLE
Dashboard scrolls up on each update

### ISSUE THREAD

**Issue by pbca26** [SuperNETorg/Iguana-application#54]
To reproduce open dashboard, make sure you have transaction history. Scroll to the bottom of the page. Wait until the next update is triggered. Expect page to be automatically scrolled to the top.

**Comment by arkadig** [comment]
@pbca26 @imboogieman Fixed, please check.

**Comment by pbca26** [comment]
@arkadig please don't forget to mention a ticket number in your commit. So we can track down what work has been done on a particular ticket.

**Comment by arkadig** [comment]
@pbca26 ok, will mention the number from now on.

**Comment by pbca26** [comment]
verified, closing
