### ISSUE TITLE
observing NaN exception when try to send transaction

### ISSUE THREAD

**Issue by kashifali00** [SuperNETorg/Iguana-application#56]
observing NaN exception when try to send transaction

Steps to reproduce:
1. Git pull
2. Run latest index.html
3. Run iguana core with fully synced coin( i was running kmd coin)
4. Click on login button
5. Select KMD coin
6. Enter passphrase
7. On dashboard click on SEND button
 here you will be observing NaN under fee column. This issue isn't troubling much but doesn't feel good also.

snapshot is attached for your perusal.
![nan](https://cloud.githubusercontent.com/assets/18286977/22394885/72bcc54e-e54e-11e6-8787-b68ed2315a7a.png)

**Comment by pbca26** [comment]
@kashifali00 fixed it yesterday. Try again.
