### ISSUE TITLE
Next BUTTON on instruction gets disabled after crash recovery of iguana core

### ISSUE THREAD

**Issue by kashifali00** [SuperNETorg/Iguana-application#57]
Next BUTTON on instruction gets disabled after crash recovery of iguana core

steps to reproduce:

1. run iguana core
2  open index.html
3. add kmd coin and login to wallet
4. wait until you see all transactions
5. ctrl+c iguana core
6. log out from wallet 
7. run iguana core again
8. click on login button
you will be observing instruction page with NEXT button disabled

**Comment by imboogieman** [comment]
@kashifali00 We have terminated coind wallet support for a moment. Instruction page concerns non-Iguana mode only. So I close this issue, as out of focus now.
