### ISSUE TITLE
wrong balance is being displayed when we get login to wallet

### ISSUE THREAD

**Issue by kashifali00** [SuperNETorg/Iguana-application#59]
wrong balance is being displayed when we get login to wallet

I understand this there is an issue with getbalance rpc if we call it for all accounts and i have informed relevant person to this but the balance on iguana gui also not correct. It should display balance of all account instead of one account. 

For reference i had two accounts on iguana core 

1. default this account is maintained for changes and it has amount of 0.9999kmds
2. iguana account is user account and it has amount of 1 kmds

so iguana gui just display 0.999 overall balance instead of accumulated balances of all account

snapshot is attached for your perusal.
![accountss](https://cloud.githubusercontent.com/assets/18286977/22406834/0f594656-e67c-11e6-80b6-2963a30ba21d.png)

**Comment by pbca26** [comment]
@kashifali00 I'm not exactly following you. If you have two accounts per one coin there's no way Iguana GUI can display that. This feature, multi-account is yet to be coded. Please confirm if my understanding is correct.

Also, have you checked getaccountbalance rpc? Is it working correctly in Iguana Core or we need to use workarounds listunspent or else?

**Comment by kashifali007** [comment]
@pbca26 getbalance rpc has an issue and its not working properly in iguana core. Fadedreamz is working on this issue. so this isn't GUI issue infact its an iguana core issue. you can mark it close.
