### ISSUE TITLE
Wrong login flow

### ISSUE THREAD

**Issue by imboogieman** [SuperNETorg/Iguana-application#61]
**Wrong:**
Given I have an Iguana account
When I login
Then I see a list of coins to add 
And the page header "wallet type"

**Right:**
Given I have an Iguana account
When I login
Then I am redirected to the dashboard
And I see coins added to the account

**Comment by imboogieman** [comment]
@arkadig pls check the referenced issue

**Comment by arkadig** [comment]
@imboogieman @pbca26 please check

**Comment by pbca26** [comment]
verified, closing
