### ISSUE TITLE
Login with wrong passphrase

### ISSUE THREAD

**Issue by imboogieman** [SuperNETorg/Iguana-application#62]
**Wrong:**
Given I have an account Iguana
When I provide a wrong passphrase
Then the next button become enabled
And I can proceed to the next step

![login with wrong passphrase_01](https://cloud.githubusercontent.com/assets/16269033/22491210/0450de00-e833-11e6-9d20-5f9f940e461b.png)
![login with wrong passphrase_02](https://cloud.githubusercontent.com/assets/16269033/22491211/045196ba-e833-11e6-9443-18d14e62b8ef.png)

**Right:**
Given I have an account Iguana
When I provide a passphrase of less than 24-words
Then I see an error message 

N.B.: The mockup shows the error message only, but the wrong input different from the requirement is considered. 24-word passphrase is required.

![login_01_6_web](https://cloud.githubusercontent.com/assets/16269033/22491159/9b6f207c-e832-11e6-9555-ed30af256455.png)

**Comment by arkadig** [comment]
@pbca26 you have commented out this part of the code 
https://github.com/SuperNETorg/Iguana-application/blob/0.3/js/controllers/loginController.js#L365
can you please explain me why ?

**Comment by pbca26** [comment]
@arkadig we don't need to check passphrase length on login as it can vary. Someone can import a wallet or create a wallet through curl or even EDEX GUI that has 4 word passphrase for example. What we should do is generate a strong passphrase for users on create wallet UI. I think you misunderstood boogieman or his instructions weren't clear enough.

Is it clear now?

**Comment by arkadig** [comment]
@pbca26 Now it's clear. Thank you.

**Comment by pbca26** [comment]
closing
hopefully this issue won't arise again
