### ISSUE TITLE
Iguana crashes on a second Full Node coin while sync

### ISSUE THREAD

**Issue by imboogieman** [SuperNETorg/Iguana-application#63]
Given I have added one coin in Full Node
And the coin is syncing
When I add another coin in Full Node
And It starts syncing
Then Iguana crashes
And I see the respective OS message

**Comment by imboogieman** [comment]
@pbca26 not sure if I shall leave this issues for the GUI repo or for the Core.

**Comment by pbca26** [comment]
@imboogieman forward this to core repo. It's not our domain.

**Comment by imboogieman** [comment]
Replaced and closed as relates to the Core development.
