### ISSUE TITLE
Iguana Mode - balance doesn't work for KMD

### ISSUE THREAD

**Issue by ed888** [SuperNETorg/Iguana-application#66]
Steps to reproduce:

Given I turned on Iguana API 
Register with KMD (native, lite, full)
Sent receive code to Roman in order to receive coins for my KMD account 
I can see the successful transaction on https://kpx.io/ but 0 on my GUI balance.
![screenshot_4](https://cloud.githubusercontent.com/assets/22639263/22587406/f7bdf152-ea1a-11e6-8a31-42d806279841.png)

**Comment by ed888** [comment]
![screenshot_3](https://cloud.githubusercontent.com/assets/22639263/22552606/0ef59b98-e973-11e6-896e-371865a381fe.png)

**Comment by pbca26** [comment]
@ed888 you need to provide more info. It's not enough to understand what's the issue.
First of all compare your wallet's address curl vs gui. Is it the same? Do you have several KDM accounts on Iguana wallet?

**Comment by ed888** [comment]
@pbca26 
_wallet's address curl vs gui. Is it the same?_
yes, that's the same 
_Do you have several KDM accounts on Iguana wallet?_ 
how can I check this ?

**Comment by pbca26** [comment]
@ed888 
>how can I check this ?

use bitcoinrpc, method listaccounts

**Comment by ed888** [comment]
@pbca26 
I logged in with the same passphrase 
did an API call with the url and userpass http://127.0.0.1:7778/api/bitcoinrpc/listaccounts?userpass=52fdfb46d171c16a13e495a5e2c5a8be&minconf=1&includewatchonly=1
this is the response of the call {"result":{"default":0},"tag":"370298723293693580"}

**Comment by pbca26** [comment]
@ed888 make sure you're running full node mode. Also, try to resync KMD coin from the scratch. Sometimes you can experience weird behaviour in Iguana Core.

Other than that I don't see any blockers. If the address on kpx matches the address in your Iguana Wallet then you should see the balance and transaction(s).

**Comment by ed888** [comment]
@pbca26 I will try to resync. I will post here about the results.

**Comment by ed888** [comment]
@pbca26 I see the balance with full mode

**Comment by pbca26** [comment]
@ed888 great. Can I close the issue? Basilisk is another story.

**Comment by ed888** [comment]
@pbca26 sure
