### ISSUE TITLE
observing NaN exception on SEND coin functionality

### ISSUE THREAD

**Issue by kashifali007** [SuperNETorg/Iguana-application#67]
observing NaN exception on SEND coin functionality

steps to reproduce:
1. Login to KMD wallet
2. Make sure you have UTXO 
3. Click on SEND button available on dashboard

on SEND button form you will be observing nan under FEE: column

snapshot is attached for your perusal.

-Kashif Ali
![nanonsend](https://cloud.githubusercontent.com/assets/16662663/22560937/2b7a575c-e998-11e6-9be8-05d09550d124.png)

**Comment by pbca26** [comment]
@kashifali007 it was due KMD not being listed on any exchange. Closing.
