### ISSUE TITLE
Add an in-app feedback tool

### ISSUE THREAD

**Issue by flamingice** [SuperNETorg/Iguana-application#9]
Something that allows the user to create a screenshot, add some text, maybe paint onto the screenshot. This would be useful for the next few versions.

edit: A list of options: https://www.quora.com/Is-there-a-feedback-plugin-that-I-can-use-for-my-web-app

**Comment by pbca26** [comment]
This might be possible with just front-end but it will be a while before and even if we can add such functionality.

**Comment by sn-cloudpipes** [comment]
What does "a while" mean in this case?

**Comment by flamingice** [comment]
What does "a while" mean in this case?

**Comment by pbca26** [comment]
1) It requires an experimental library that doesn't always do a good work in capturing screenshots.
2) To be able to draw anything over a captured screenshot we need to add such functionality.
3) For smooth integration there is a need for a backend server that can "grab" feedback sent from within the gui.

There are certain apps or even browser extensions that you can leverage to capture sreenshots for now.

**Comment by flamingice** [comment]
http://blog.instabug.com/2015/06/6-reasons-why-in-app-feedback-is-a-must-while-beta-testing/
